export const classicTemplate = {
  id: 'classic' as const,
  name: 'Classic',
  description: 'Single column, generous margins. Clean & corporate.',
  marginTop: 72,
  marginBottom: 72,
  marginLeft: 90,
  marginRight: 90,
  pageWidth: 612,
  pageHeight: 792,
  titleSize: 26,
  headingSize: 18,
  subheadingSize: 14,
  bodySize: 11,
  lineHeight: 16,
  sectionSpacing: 24,
  paragraphSpacing: 10,
  fieldHeight: 24,
  textareaHeight: 60,
  bulletIndent: 14,
  headerBarHeight: 0,
  twoColumn: false,
  notesColumnWidth: 0,
};
