export const modernTemplate = {
  id: 'modern' as const,
  name: 'Modern',
  description: 'Bold section headers with color bar. Contemporary feel.',
  marginTop: 60,
  marginBottom: 60,
  marginLeft: 72,
  marginRight: 72,
  pageWidth: 612,
  pageHeight: 792,
  titleSize: 28,
  headingSize: 16,
  subheadingSize: 13,
  bodySize: 11,
  lineHeight: 16,
  sectionSpacing: 28,
  paragraphSpacing: 8,
  fieldHeight: 26,
  textareaHeight: 64,
  bulletIndent: 14,
  headerBarHeight: 6,
  twoColumn: false,
  notesColumnWidth: 0,
};
