export const workbookTemplate = {
  id: 'workbook' as const,
  name: 'Workbook',
  description: 'Two-column with notes column on right (30%). Education & coaching.',
  marginTop: 60,
  marginBottom: 60,
  marginLeft: 72,
  marginRight: 72,
  pageWidth: 612,
  pageHeight: 792,
  titleSize: 24,
  headingSize: 16,
  subheadingSize: 13,
  bodySize: 11,
  lineHeight: 16,
  sectionSpacing: 22,
  paragraphSpacing: 8,
  fieldHeight: 24,
  textareaHeight: 60,
  bulletIndent: 14,
  headerBarHeight: 0,
  twoColumn: true,
  notesColumnWidth: 0.30, // fraction of content width
};
